# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0006_chatmessage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocket',
            fields=[
                ('reply_channel', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
