# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0007_websocket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('state', models.CharField(choices=[('s1', 's1'), ('t1', 't1'), ('w1', 'w1'), ('g1', 'g1'), ('g2', 'g2'), ('s2', 's2'), ('t2', 't2'), ('w3', 'w3'), ('s3', 's3'), ('t3', 't3'), ('g31', 'g31'), ('g32', 'g32'), ('g33', 'g33')], default='s1', max_length=20)),
                ('money_earned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('groups', models.ManyToManyField(to='core.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeror', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserState',
        ),
        migrations.AddField(
            model_name='group',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
