# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_create_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websocket',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebSocket',
        ),
    ]
