# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170301_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=30, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
                ('url_name', models.CharField(max_length=200)),
                ('allowed_user_states', models.ManyToManyField(related_name='allowed_states_admin', to='core.GameStates')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GameStates'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GameStates'),
        ),
    ]
