# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170303_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Game'),
            preserve_default=False,
        ),
    ]
